name = "astro-blog"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[vars]
PUBLIC_CDN_URL = "https://cdn.virtuallyanadmin.com"
SONICJS_API_URL = "https://my-sonicjs-app.going2timbuktu.workers.dev"
